name: User Support
description: "Use this if you need help with something, or you're experiencing an issue."
labels: [ "User Support" ]
body:
    - type: markdown
      attributes:
        value: |
            Before submitting a **User Report** issue, please ensure the following:

            **1:** You are running the latest version of SwarmUI. You can go to `Server` -> then press `Update and Restart` to update.
            **2:** You have made an effort to find public answers to your question before asking here. In other words, you googled it first, and scrolled through recent help topics. It's also wise to do a CTRL+F search on the [SwarmUI Discord](https://discord.gg/q2y38cqjNw).

            In general we recommend most support questions go through the [SwarmUI Discord](https://discord.gg/q2y38cqjNw).
    - type: textarea
      attributes:
            label: Your question
            description: "Post your question here. Please be as detailed as possible."
      validations:
            required: true
    - type: textarea
      attributes:
                label: Logs
                description: "If your question relates to an issue you're experiencing, please go to `Server` -> `Logs` -> then click the `Pastebin` button and copy the link it generates for you to here. Alternately, set `View Type` to `Debug` as well, then copypaste all the text into here."
      validations:
                required: false
    - type: textarea
      attributes:
                label: Other
                description: "Any other additional information you think might be helpful."
      validations:
                required: false
