services:
  swarmui:
    image: swarmui:latest # You should build the image first. run "sudo docker build -f launchtools/StandardDockerfile.docker -t swarmui ." 
                          # in the SwarmUI folder on the docker host. Optionally, push to your own registry so the Docker Swarm can deploy
                          # automatically from your registry. Otherwise, you must build this image on each worker/manager that will be running
                          # SwarmUI
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}
    cap_drop:
      - ALL
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
      dockerfile: launchtools/StandardDockerfile.docker
    # uncomment `network_mode: host` if you want to access other services on the host network (eg a separated comfy instance)
    # network_mode: host
    volumes:
      - swarmui-data-sync:/SwarmUI/Data
      - swarmui-dlbackend-sync:/SwarmUI/dlbackend
      - swarmui-dlnodes-sync:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
      - swarmui-extensions-sync:/SwarmUI/src/Extensions
      - swarmui-models-sync:/SwarmUI/Models
      - swarmui-output-sync:/SwarmUI/Output
      - swarmui-comfyui-sync:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
    ports:
      - "7801:7801"
    deploy:
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'AMD_GPU'   # Matches daemon.json key
                value: 0          # See https://instinct.docs.amd.com/projects/container-toolkit/en/latest/container-runtime/docker-swarm.html for Docker AMD GPU setup

volumes:
  swarmui-data-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-dlbackend-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-dlnodes-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-extensions-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-models-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-comfyui-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
  swarmui-output-sync:
    driver: local
    driver_opts:
      type: nfs
      device: ":<PATH-TO-YOUR-NFS-SHARE>"
      o: "addr=<NFS-IP-ADDR>,nolock,soft,rw"
