name: Unit Tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
          with:
            fetch-depth: 0
            fetch-tags: true
        - uses: actions/setup-dotnet@v5
          with:
            dotnet-version: '8.x'
        - run: bash ./launchtools/run_tests.sh
