using ATL;
using FreneticUtilities.FreneticExtensions;
using Newtonsoft.Json.Linq;
using SwarmUI.Utils;
using System.IO;

namespace SwarmUI.Media;

/// <summary>A simple audio file (eg mp3, wav).</summary>
public class AudioFile : MediaFile
{
    /// <summary>Creates an audio object from a web audio data URL string.</summary>
    public static AudioFile FromDataString(string data)
    {
        byte[] raw = Convert.FromBase64String(data.After(";base64,"));
        string mimeType = data.Before(";base64,").After("data:");
        return new AudioFile(raw, MediaType.TypesByMimeType.GetValueOrDefault(mimeType) ?? new(mimeType.After('/'), mimeType, MediaMetaType.Audio));
    }

    /// <summary>Creates an audio object from a base64 string and media type.</summary>
    public static AudioFile FromBase64(string b64, MediaType type)
    {
        byte[] raw = Convert.FromBase64String(b64);
        return new AudioFile(raw, type);
    }

    /// <inheritdoc/>
    public override string GetMetadata()
    {
        try
        {
            using MemoryStream stream = new(RawData, false);
            string metadata = new Track(stream).Comment;
            return string.IsNullOrWhiteSpace(metadata) ? null : metadata;
        }
        catch (Exception ex)
        {
            Logs.Error($"Metadata read for audio failed: {ex.ReadableString()}");
            return null;
        }
    }

    /// <summary>Gets the metadata JSON from an audio file generated by this program.</summary>
    public JObject GetSUIMetadata()
    {
        return GetSUIMetadata(GetMetadata());
    }

    /// <summary>Returns a copy of this audio file with the given metadata embedded.</summary>
    public AudioFile WithMetadata(string metadata)
    {
        using MemoryStream stream = new(RawData.Length + 1024);
        stream.Write(RawData);
        stream.Position = 0;
        Track track = new(stream)
        {
            Comment = metadata
        };
        track.Save();
        return new AudioFile(stream.ToArray(), Type);
    }

    /// <summary>Construct the audio instance from raw data and a media type.</summary>
    public AudioFile(byte[] data, MediaType type)
    {
        RawData = data;
        Type = type;
    }
}
