using ATL;
using FreneticUtilities.FreneticExtensions;
using Newtonsoft.Json.Linq;
using SwarmUI.Utils;
using System.IO;

namespace SwarmUI.Media;

/// <summary>A video file (eg mp4) containing image data, audio data, metadata, and possibly other sub-streams of data.</summary>
public class VideoFile : MediaFile
{
    /// <summary>Creates a video object from a web video data URL string.</summary>
    public static VideoFile FromDataString(string data)
    {
        byte[] raw = Convert.FromBase64String(data.After(";base64,"));
        string mimeType = data.Before(";base64,").After("data:");
        return new VideoFile(raw, MediaType.TypesByMimeType.GetValueOrDefault(mimeType) ?? new(mimeType.After('/'), mimeType, MediaMetaType.Video));
    }

    /// <summary>Creates a video object from a base64 string and media type.</summary>
    public static VideoFile FromBase64(string b64, MediaType type)
    {
        byte[] raw = Convert.FromBase64String(b64);
        return new VideoFile(raw, type);
    }

    /// <inheritdoc/>
    public override string GetMetadata()
    {
        try
        {
            using MemoryStream stream = new(RawData, false);
            string metadata = new Track(stream).Comment;
            return string.IsNullOrWhiteSpace(metadata) ? null : metadata;
        }
        catch (Exception ex)
        {
            Logs.Error($"Metadata read for video failed: {ex.ReadableString()}");
            return null;
        }
    }

    /// <summary>Gets the metadata JSON from a video file generated by this program.</summary>
    public JObject GetSUIMetadata()
    {
        return GetSUIMetadata(GetMetadata());
    }

    /// <summary>Returns a copy of this video file with the given metadata embedded.</summary>
    public VideoFile WithMetadata(string metadata)
    {
        using MemoryStream stream = new(RawData.Length + 1024);
        stream.Write(RawData);
        stream.Position = 0;
        Track track = new(stream)
        {
            Comment = metadata
        };
        track.Save();
        return new VideoFile(stream.ToArray(), Type);
    }

    /// <summary>Construct the video instance from raw data and a media type.</summary>
    public VideoFile(byte[] data, MediaType type)
    {
        RawData = data;
        Type = type;
    }
}
